<?php

return array(
    'hooks'    => array(
        array(
            'event'    => 'beforeAnyCrmRequest',
            'callback' => "Extension\\DelayedTransactions\\AdvancedDelay@passThroughDelayModule",
            'priority' => 101,
        ),
        array(
            'event'    => 'beforeAnyCrmRequest',
            'callback' => "Extension\\DelayedTransactions\\Hooks@passThroughDelayModule",
            'priority' => 100,
        ),
        array(
            'event'    => 'pageLoad',
            'callback' => "Extension\\DelayedTransactions\\AdvancedDelay@processCurrentOrders",
            'priority' => 501,
        ),
        array(
            'event'    => 'pageLoad',
            'callback' => "Extension\\DelayedTransactions\\Hooks@processCurrentOrders",
            'priority' => 500,
        ),
    ),
    'custom_html' => array(
        'template_js' => 'js/delaytransaction.js',
        'enable' => true,
        'template_name' => 'html/delaytransaction.html'
    ),
    'routes'   => array(
        array(
            'slug'     => 'process-orders',
            'callback' => "Extension\\DelayedTransactions\\Crons@processOrders",
        ),
        array(
            'slug'     => 'reprocess-orders',
            'callback' => "Extension\\DelayedTransactions\\Hooks@reprocessOrders",
            'method'   => "post",
        ),
    ),

    'crons'    => array(
        array(
            'every'   => '* * * * *',
            'handler' => 'Extension\DelayedTransactions\Crons@processOrders',
            'overlap' => false,
        ),
        array(
            'every'   => '*/5 * * * *',
            'handler' => 'Extension\DelayedTransactions\Crons@clrPayload',
            'overlap' => false,
        ),
    ),
    'actions'  => array(
        'save' => "Extension\\DelayedTransactions\\Actions@save",
    ),

    'settings' => array(
        array(
            'label' => 'Table Name',
            'key'   => 'table_name',
            'type'  => 'string',
            'value' => '',
            'hint'  => 'Database table name, Where delayed order records will be saved.',
        ), array(
            'label' => 'Authorization Amount',
            'key'   => 'authorization_amount',
            'type'  => 'string',
            'value' => '',
            'hint'  => 'Authorization amount required for authorizing Credit Card',
        ),
        array(
            'label' => 'Enable Multiple Authorization Amount',
            'key'   => 'enable_multiple_auth_amount',
            'type'  => 'boolean',
            'value' => false,
        ),
        array(
            'label'    => 'Multiple Authorization Amount',
            'key'      => 'multiple_auth_amount',
            'type'     => 'string',
            'textarea' => true,
            'value'    => '',
            'optional' => true,
            'hint'     => 'CARDTYPE | AUTHORIZATION AMOUNT in new line',
        ),
        array(
            'label' => 'Retry PreAuthorization',
            'key'   => 'retry_preauth',
            'type'  => 'boolean',
            'value' => false,
            'flex'  => 100
        ),
        array(
            'label' => 'Retry Authorization Amount',
            'key'   => 'retry_authorization_amount',
            'type'  => 'string',
            'value' => '',
            'hint'  => 'Enter Retry Authorization Amount',
            'optional' => true,
        ),
        array(
            'label' => 'Retry Authorization Campaign',
            'key'   => 'retry_preauth_campaign',
            'type'  => 'string',
            'value' => '',
            'hint'  => 'Enter Retry Authorization Campaign',
            'optional' => true,
        ),
        array(
            'label'    => 'Ignore Steps',
            'key'      => 'ignore_steps',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add steps in CSV format to exclude from combine (i.e 1,2)',
        ),
        array(
            'label' => 'Combine Steps',
            'key'   => 'combine_steps',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Place all orders (Excluding Split Order) as a single order.',
        ),
        array(
            'label' => 'Combine Split',
            'key'   => 'combine_split',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Combine Split Orders with other delayed orders.',
        ),
        array(
            'label' => 'Process Orders At Thank You Page',
            'key'   => 'process_orders_at_thankyou',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Process Orders At Thank You Page.',
        ),
        array(
            'label' => 'Ignore PreAuthorization',
            'key'   => 'ignore_preauth',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Ignore PreAuthorization at checkout.',
            'flex'  => 100,
        ),
        array(
            'label' => 'Enable Preauth Log',
            'key'   => 'enable_preauth_log',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Store pre auth response from CRM.',
        ),
        array(
            'label'    => 'Pre Auth Log Table Name',
            'key'      => 'preauth_log_table_name',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Database table name, Where pre-auth transaction records will be saved.',
        ),
        array(
            'label' => 'Advanced Delay',
            'key'   => 'advanced_delay',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Enable Advanced Delay.',
        ),
        array(
            'label'    => 'Update steps',
            'key'      => 'update_steps',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add steps in CSV format to exclude from combine (i.e 1,2). Also make sure the delay option is disabled in configuration section for this step(s).',
        ),
        array(
            'label'    => 'Order processing steps',
            'key'      => 'order_processing_steps',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add step where the orders will be processed',
        ),
        array(
            'label' => 'Reprocess Declined order',
            'key'   => 'reprocess_decline',
            'type'  => 'boolean',
            'value' => false,
            'hint'  => 'Reprocess Declined order.',
        ),
        array(
            'label'    => 'Reprocessing Codebase Campaign Id',
            'key'      => 'reprocess_campaignId',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add Codebase Campaign Id by which Declined orders will be processed.',
        ),
        array(
            'label'    => 'Declined Reason',
            'key'      => 'declined_reason',
            'type'     => 'string',
            'textarea' => true,
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add Declined Reason.',
            'flex'     => 100,
        ),
        array(
            'label' => 'Bypass Kount session post',
            'key'   => 'bypass_kount_session',
            'type'  => 'boolean',
            'value' => false,
        ),
        array(
            'label' => 'Enable Membership',
            'key'   => 'enable_membership',
            'type'  => 'boolean',
            'value' => false,
            'flex'  => 100,
        ),
        array(
            'label'    => 'Membership Config ID',
            'key'      => 'membership_config',
            'type'     => 'string',
            'value'    => "",
            'optional' => true,
        ),
        array(
            'label'    => 'Membership Create Event ID',
            'key'      => 'membership_create_event_id',
            'type'     => 'string',
            'value'    => "",
            'optional' => true,
        ),
        array(
            'label' => 'Enable Datacapture',
            'key'   => 'enable_datacapture',
            'type'  => 'boolean',
            'value' => false,
            'flex'  => 100,
        ),
        array(
            'label' => 'Enable Native Datacapture',
            'key'   => 'enable_native_datacapture',
            'type'  => 'boolean',
            'value' => false,
        ),
        array(
            'label'    => 'Native Datacapture Table',
            'key'      => 'native_datacapture_table',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
        ),
        array(
            'label' => 'Ignore split charge for advance flow',
            'key'   => 'ignore_split_charge_for_advance_flow',
            'type'  => 'boolean',
            'value' => false,
        ),
        array(
            'label' => 'Allow HTML pixel fire for delay',
            'key'   => 'allow_pixel_fire_for_delay',
            'type'  => 'boolean',
            'value' => false,
        ),
        array(
            'label' => 'Enable Prepaid Redirection',
            'key'   => 'prepaid_redirection_enabled',
            'type'  => 'boolean',
            'value' => false,
            'flex'  => 100,
        ),
        array(
            'label'    => 'Prepaid Redirection URL for desktop',
            'key'      => 'prepaid_redirection_url',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
        ),
        array(
            'label'    => 'Prepaid Redirection URL for mobile',
            'key'      => 'prepaid_redirection_url_mobile',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
        ),
        array(
            'label'    => 'Cache clean of successful orders',
            'key'      => 'clr_payload_duration_success_orders',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add in minutes, if not provided default time will be used',
        ),
        array(
            'label'    => 'Cache clean of decline orders',
            'key'      => 'clr_payload_decline_orders',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Add in minutes, if not provided default time will be used',
        ),
        array(
            'label' => 'Allow original method (For Konnektive)',
            'key' => 'allow_original_method',
            'type' => 'boolean',
            'value' => false,
        ),
        array(
            'label'    => 'Bypass Order View Steps',
            'key'      => 'bypass_orderview_steps',
            'type'     => 'string',
            'value'    => '',
            'optional' => true,
            'hint'     => 'Comma separated',
        ),
    ),
);
